version: '3.6'
services:
  cosmosdb:
    image: mcr.microsoft.com/cosmosdb/linux/azure-cosmos-emulator
    hostname: cosmosdb
    container_name: cosmosdb
    mem_limit: 3g
    cpus: 2.0
    ports:
      - '8081:8081'
      - '10251:10251'
      - '10252:10252'
      - '10254:10254'
    environment:
      - AZURE_COSMOS_EMULATOR_PARTITION_COUNT=10
      - AZURE_COSMOS_EMULATOR_ENABLE_DATA_PERSISTENCE=true
      - AZURE_COSMOS_EMULATOR_IP_ADDRESS_OVERRIDE=127.0.0.1
  cosmosdb-setup:
    environment:
      - CONNECTION_STRING=AccountEndpoint=https://127.0.0.1:8081/;AccountKey=C2y6yDjf5/R+ob0N8A7Cgv30VRDJIWEHLM+4QDU5DE2nQ9nDuVTqobD4b8mGGyPMbIZnqyMsEcaGQy67XIw/Jw==
    network_mode: host
    image: robinmanuelthiel/cosmos-db-setup:2.0.0
    command:
      - "{\"databaseName\": \"infrastructuredbtests\", \"containers\": [{\"name\": \"users\", \"partitionKey\": \"/tenantId\"}, {\"name\": \"datacenters\", \"partitionKey\": \"/partitionKey\"}]}"
    depends_on:
      - cosmosdb
